### ISSUE TITLE
Container transform examples don't fade

### ISSUE THREAD

**Issue by jonasnaimark** [serbelga/Material-Motion-Samples#1]
Not sure if this is an issue with the screen recording, but in the examples the views don't fade during the transition. Instead they instantly jump from the FAB to the Details page:

https://miro.medium.com/max/1024/1*w_auOSonYemMyiUTyA9NrQ.gif

Here's how it looks on my device with the correct fading:

https://drive.google.com/file/d/1C5iIjubhOx3jCVS3PB8cnnQ4RU4Xm838/view?usp=sharing

**Comment by serbelga** [comment]
https://github.com/serbelga/Material-Motion-Samples/blob/696256c9c141663571f5a3c6f1ab6076e739f83e/app/src/main/java/com/example/sergiobelda/materialmotion/notes/AddNoteActivity.kt#L37 
I've removed the start view and end view background, and I'm using this function to achieve that behaviour
https://github.com/serbelga/Material-Motion-Samples/blob/master/screenshots/fab_to_activity_slow.gif
