### ISSUE TITLE
Shared axis outgoing view doesn't animate

### ISSUE THREAD

**Issue by jonasnaimark** [serbelga/Material-Motion-Samples#2]
The outgoing view for each shared axis example instantly disappears:

https://drive.google.com/file/d/1yXFKYWZXqNW49d-MBgGGUiqQp4DGSYCl/view?usp=sharing

Ideally it should fade out + slide in x, y or z. This is best seen in slow motion here:

https://github.com/material-components/material-components-android/blob/master/docs/theming/assets/motion/shared_axis_lineup.gif

**Comment by serbelga** [comment]
I've applied a SharedAxis transition as exit transition for the fragment that will be replaced
https://github.com/serbelga/Material-Motion-Samples/blob/57b25ee9b78befc15467507c241934aa014941e2/app/src/main/java/com/example/sergiobelda/materialmotion/walkthrough/WalkthroughActivity.kt#L95

https://github.com/serbelga/Material-Motion-Samples/blob/master/screenshots/shared_axis_x.gif
https://github.com/serbelga/Material-Motion-Samples/blob/master/screenshots/shared_axis_y.gif
https://github.com/serbelga/Material-Motion-Samples/blob/master/screenshots/shared_axis_z_2.gif

It should be noted that when this change is applied to the Z axis in the example, the TextInputLayout have strange behavior
