### ISSUE TITLE
Make for fragments

### ISSUE THREAD

**Issue by vladsakun2** [serbelga/Material-Motion-Samples#6]
Hi Sergio Belda Galbis, thanks a lot for your samples. I am confused how to do the back transition from Fragment to FAB. So please make FAB animations for Fragments. Or may be I can share my code with you and you will help me to do back animation. I have animation from Fragment A to Fragment B on FAB click, but I can not do back animation to FAB. Like this example:

![image](https://user-images.githubusercontent.com/71494904/101022105-9a3dfa00-3579-11eb-8c6d-a42bf0b2b439.png)

in Material documentation: https://material.io/develop/android/theming/motion

**Comment by serbelga** [comment]
I'll see if I can add an example

**Comment by Kevinnad** [comment]
Looking for the same, Please add an example with fragments

**Comment by serbelga** [comment]
With #9, I updated the Music sample to see an example when a Card is transformed in a Detail Fragment from the List Fragment. You can apply this in the image that you have put but instead of having a Card as your shared element, you would use the Floating Action Button.
